In [2]:
import pandas as pd
import numpy as np
import scipy
import scipy.stats

In [3]:
df = pd.read_csv('bicicletas-compartidas.csv')

In [4]:
df.columns

Index(['fecha', 'bicis-compartidas', 'temp-obs', 'sens-temp', 'hum', 'viento',
       'codigo-clima', 'festivo', 'findesemana', 'cuartil-ano'],
      dtype='object')

# Frecuencias categoricas

In [17]:
ycat = df['cuartil-ano']
ycat

0        3.0
1        3.0
2        3.0
3        3.0
4        3.0
        ... 
17409    3.0
17410    3.0
17411    3.0
17412    3.0
17413    3.0
Name: cuartil-ano, Length: 17414, dtype: float64

In [18]:
ycat = ycat.apply(lambda x: 'Cat-' + str(int(x)))
ycat.head()

0    Cat-3
1    Cat-3
2    Cat-3
3    Cat-3
4    Cat-3
Name: cuartil-ano, dtype: object

In [20]:
valores, conteo_freq = np.unique(ycat, return_counts = True)
valores, conteo_freq

(array(['Cat-0', 'Cat-1', 'Cat-2', 'Cat-3'], dtype=object),
 array([4394, 4387, 4303, 4330]))

In [21]:
tabla_frecuencias = dict(zip(valores, conteo_freq))
tabla_frecuencias

{'Cat-0': 4394, 'Cat-1': 4387, 'Cat-2': 4303, 'Cat-3': 4330}

# Variable numerica

In [22]:
ynum = df['viento'].copy()
np.min(ynum), np.max(ynum)

(0.0, 56.5)

In [37]:
np.percentile(ynum, q=100)

56.5

In [25]:
np.percentile(ynum, q=0)

0.0

In [26]:
np.percentile(ynum, q=50)

15.0

In [28]:
np.median(ynum)

15.0

In [29]:
valores = [0, 25, 50, 75, 100]
np.percentile(ynum, q = valores)

array([ 0. , 10. , 15. , 20.5, 56.5])

In [30]:
valores = [0, 20, 40, 60, 80, 100]
np.percentile(ynum, q = valores)

array([ 0. ,  9. , 13. , 17. , 22. , 56.5])

In [32]:
valores = list(range(0,110,10))
np.percentile(ynum, q = valores)

array([ 0. ,  6.5,  9. , 11. , 13. , 15. , 17. , 19.5, 22. , 27. , 56.5])

In [33]:
y = df['bicis-compartidas']
y.describe()

count    17414.000000
mean      1143.101642
std       1085.108068
min          0.000000
25%        257.000000
50%        844.000000
75%       1671.750000
max       7860.000000
Name: bicis-compartidas, dtype: float64

In [40]:
# outlier es el valor atipico, se requiere calcular el q1 y q3 y el rango intercuartiligo, hay que definir los limites inferiores y superiores
Q1 = np.percentile(y, q=25)
Q2 = np.percentile(y, q=75)

RI = Q2 - Q1

lim_inf = Q1 - 1.5 * RI
lim_sup = Q2 + 1.5 * RI

[lim_inf, lim_sup]

[-1865.125, 3793.875]

In [ ]:
import matplotlin.pyplot as plt
